# Generated by Django 4.0.8 on 2022-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('incident_department', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('incident_location', models.CharField(max_length=50)),
                ('initial_severity', models.CharField(max_length=50)),
                ('immidiate_action_taken', models.CharField(max_length=100)),
                ('enviornmentalincident', models.BooleanField(default=False)),
                ('injury_illness', models.BooleanField(default=False)),
                ('property_damage', models.BooleanField(default=False)),
                ('vehicle', models.BooleanField(default=False)),
                ('reported_by', models.CharField(max_length=50)),
            ],
        ),
    ]
