# Generated by Django 4.0.8 on 2022-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_personalcontacts_incidentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdata',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='immidiate_action_taken',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='incident_department',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='incident_location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='initial_severity',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='reported_by',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
