# Generated by Django 4.0.8 on 2022-11-20 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_incidentdata_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdata',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
